[project]
name = "ai-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.14.0",
    "pydantic>=2.12.5",
    "tiktoken>=0.12.0",
]
